#!/bin/bash

# ========================================
#| description     : install bash .files  |
#| author          : Ramanpreet Singh     |
# ========================================

DOTFILES_DIR=$(dirname $(dirname $(readlink -f $0)))

echo "Making Symbolic Links"
rm -f ~/.profile
ln -s -f $DOTFILES_DIR/bash/profile.sh $HOME/.profile
mkdir -p $HOME/.config
ln -s -f $DOTFILES_DIR/bash/starship.toml $HOME/.config/starship.toml
ln -s -f $DOTFILES_DIR/vimrc $HOME/.vimrc
ln -s -f $DOTFILES_DIR/gitconfig $HOME/.gitconfig
ln -s -f $DOTFILES_DIR/ssh-config $HOME/.ssh/config
echo "... Done"

# the default .bashrc file lives in /etc/skel/.bashrc
echo "Updating .bashrc"
echo "copying default .bashrc file to $HOME"
cp /etc/skel/.bashrc $HOME/.bashrc
if [[ -f $HOME/.bashrc ]]; then
  echo '' >>$HOME/.bashrc
  echo '# Customizations start' >>$HOME/.bashrc
  echo '# Generated by dotfiles' >>$HOME/.bashrc
  echo '# append local bin to PATH' >>$HOME/.bashrc
  echo -e 'if [[ -d ~/.local/bin ]]; then\n  PATH=~/.local/bin:$PATH\nfi' >>$HOME/.bashrc
  echo '' >>$HOME/.bashrc
  echo "# history" >>$HOME/.bashrc
  echo 'export HISTCONTROL=ignoreboth:erasedups' >>$HOME/.bashrc
  echo 'export HISTFILESIZE=1000000' >>$HOME/.bashrc
  echo 'export HISTSIZE=1000000' >>$HOME/.bashrc
  echo '' >>$HOME/.bashrc
  echo '# starship' >>$HOME/.bashrc
  echo 'eval "$(starship init bash)"' >>$HOME/.bashrc
  echo '' >>$HOME/.bashrc
  echo '# fzf' >>$HOME/.bashrc
  echo -e 'if [[ -f ~/.fzf.bash ]]; then\n  source ~/.fzf.bash\nfi' >>$HOME/.bashrc
  echo '' >>$HOME/.bashrc
  echo '# diff-so-fancy' >>$HOME/.bashrc
  echo -e 'if [[ -d ~/.diff-so-fancy ]]; then\n  export PATH=~/.diff-so-fancy:$PATH\nfi' >>$HOME/.bashrc
  echo '' >>$HOME/.bashrc
  echo '# Customizations end' >>$HOME/.bashrc
fi

echo "Installing diff-so-fancy"
if [[ -d $HOME/.diff-so-fancy ]]; then
  rm -rf $HOME/.diff-so-fancy
fi
git clone https://github.com/so-fancy/diff-so-fancy.git $HOME/.diff-so-fancy
echo "... Done"

echo "Installing fzf"
if [[ -d $HOME/.fzf ]]; then
  rm -rf $HOME/.fzf
  rm $HOME/.fzf.*
fi
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install --key-bindings --completion --no-update-rc --no-zsh --no-fish
echo "... Done"

echo "Installing starship"
if [[ -f $HOME/.local/bin/starship ]]; then
  rm $HOME/.local/bin/starship
fi
mkdir -p $HOME/.local/bin
curl -sS https://starship.rs/install.sh | sh -s -- --bin-dir $HOME/.local/bin --yes
chmod +x $HOME/.local/bin/starship
echo "... Done"

exit 1
